stack/urls.py
from django.urls import re_path
from stack import views

urlpatterns = [
    re_path('^$', views.home, name="stack_question_home"),
    re_path('^all/$', views.QuestionList.as_view(), name="stack_question_list"),
    re_path('^add/$', views.add, name="stack_question_add"),
    re_path('^preview/$', views.preview, name="stack_question_preview"),
    re_path('^(?P<slug>[^/]+)/$', views.detail, name="stack_question_detail"),
    re_path('^(?P<slug>[^/]+)/accepted-answer/(?P<comment>[^/]+)/$', views.accepted_answer, name="stack_accepted_answer"),
]

stack/models.py
from django.db import models
import datetime
import random
from django.template.defaultfilters import slugify
from django.db import IntegrityError
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.conf import settings
import django_comments
from djangoratings.fields import RatingField

Comment = django_comments.get_model()


def SlugifyUniquely(value, model, slugfield="slug"):
    """Returns a slug on a name which is unique within a model's table

    This code suffers a race condition between when a unique
    slug is determined and when the object with that slug is saved.
    It's also not exactly database friendly if there is a high
    likelyhood of common slugs being attempted.

    A good usage pattern for thrandom
    is code would be to add a custom save()
    method to a model with a slug field along the lines of:

    from django.template.defaultfilters import slugify

    def save(self):
    if not self.id:
    # replace self.name with your prepopulate_from field
    self.slug = SlugifyUniquely(self.name, self.__class__)
    super(self.__class__, self).save()

    Original pattern discussed at
    http://www.b-list.org/weblog/2006/11/02/django-tips-auto-populated-fields
    """
    MAX_SUFFIX_LENGTH = getattr(settings, 'MAX_SUFFIX_LENGTH', 3)
    SUFFIX_CHARS = getattr(settings, 'SUFFIX_CHARS', 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ')
    SLUGIFY_MAX_ATTEMPTS = getattr(settings, 'SLUGIFY_MAX_ATTEMPTS', 250)
    max_length = model._meta.get_field(slugfield).max_length
    potential = base = slugify(value)
    date = datetime.date.today().strftime("%d-%m-%y")

    def random_suffix_generator(size=MAX_SUFFIX_LENGTH, chars=SUFFIX_CHARS):
        """
        Generates a random string of length determined by size and using the
        alphabet indicated by chars.
        """
        return ''.join(random.choice(chars) for i in range(size))
    
    for attempt in range(SLUGIFY_MAX_ATTEMPTS):
        old_potential = potential
        random_suffix = random_suffix_generator()
        try:
            # For the first try (0) just use the base
            # For the next 5 tries, just add a number
            if 5 > attempt > 0:
                potential = '%s-%s' % (base[:max_length - 2], attempt)
            # One try with just the date
            if attempt == 5:
                potential = '%s-%s' % (date, base)
            # Everything else failed,
            # use the date plus a random suffix for the rest
            elif attempt > 5:
                potential = '%s-%s-%s' % (date, random_suffix, base)

            # Cut it to the max length of the model slug field.
            potential = potential[:max_length]
            model.objects.get(**{slugfield: potential})

            if attempt > 0 and potential == old_potential:
                # Then, the next iteration will be the same, just stop.
                raise Exception("SlugifyUnique: not able to generate an unique slug. (%s)" % potential)
        except model.DoesNotExist:
            # Good, we found one.
            return potential

    # Oh noo! Max attempts reached.
    raise Exception("SlugifyUnique: Max attempts reached. (%s) last value: %s" % (SLUGIFY_MAX_ATTEMPTS, potential))


class Question(models.Model):
    site = models.ForeignKey('sites.Site', on_delete=models.PROTECT)
    comment = models.OneToOneField(Comment, on_delete=models.CASCADE, null=True)  # Null because it needs to be saved first
    rating = RatingField(can_change_vote=True, allow_anonymous=True, range=1, editable=False)
    title = models.CharField(max_length=250, verbose_name="Question")
    slug = models.CharField(max_length=255)
    views = models.IntegerField(editable=False, default=0, db_column="view_count_cache")
    accepted_answer = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="accepted_answers", null=True, blank=True)
    has_answer = models.BooleanField(default=False)
    closed = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title.replace("[[", "").replace("]]", "")

    def __str__(self):
        return self.title.replace("[[", "").replace("]]", "")

    def get_response_count(self):
        return Comment.objects.filter(
            content_type=ContentType.objects.get_for_model(self),
            object_pk=self.pk).count() - 1  # One is the actual question

    def get_absolute_url(self):
        return reverse("stack_question_detail", args=[self.slug])

    def save(self, *args, **kwargs):
        self.site = Site.objects.get_current()
        if not self.slug:
            self.generate_slug()

        if self.accepted_answer_id:
            self.has_answer = True

        while True:
            try:
                super(Question, self).save(*args, **kwargs)
                return
            except IntegrityError:
                self.generate_slug()

    def generate_slug(self):
        length = Question._meta.get_field('title').max_length
        self.title = self.title[:length]
        self.slug = SlugifyUniquely(self.title, Question)
        if not self.slug:
            self.slug = SlugifyUniquely("question", Question)

stack/templates/stack/add.html
{% extends "base.html" %}
{% block body %}
<div class="span-14">
	<h2>Ask a question</h2>
	<form action="../preview" method="post">{% csrf_token %}
		{% for field in form %}
		<p>
			{{ field.label_tag }}
			{{ field }}<br />
			{{ field.help_text }}
			{{ field.errors }}
		</p>
		{% endfor %}
		<input type='submit' name='preview' value='{% trans "Preview Question" %}' />
	</form>
</div>
{% endblock %}

stack/templates/stack/answer_stage.html
{% load comments_plus_tags stack_tags comments wiki_tags subscription_tags %}
{% get_answer_list for object as comment_list %}
<div class="comment-content">
    {% if comment_list %}
    <div id="comments" class="span-17">
        {% for comment in comment_list %}
        {% if comment.is_public %}
        <div class="answer comment span-17 prepend-top{% if object.accepted_answer_id == comment.pk %} accepted-answer{% endif %}" id="c{{ comment.pk }}">
            <div class="rating-box span-2" style="text-align:center;">
                <div class="span-2">
                    Rating:<br />
                    <span style="font-size:30px !important;" href="#">
                        {{ comment.karma__count }}{% if user.is_authenticated %}<a href="" class="comment-karma-add">+</a>{% endif %}
                    </span>
                </div>
                {% if user == object.comment.user or perms.stack.change_question %}
                {% if not object.accepted_answer_id == comment.pk %}
                <div class="span-2">
                    <a href="{% url stack_accepted_answer object.slug comment.pk %}">Make accepted answer</a>
                </div>
                {% endif %}
                {% endif %}
                {% if object.accepted_answer_id == comment.pk %}
                <div class="span-2" style="font-weight:bold;">
                    Accepted Answer
                </div>
                {% endif %}
            </div>
            <div class="span-15 last">
                <div class="top span-15">
                    <div class="span-8">
                        <a class="comment-page-id" href="#comment-{{ forloop.counter }}" id="comment-{{ forloop.counter }}">#{{ forloop.counter }}</a> |
                        {% display_username comment.user_id %} says...
                    </div>
                    <div class="span-7 last" style="text-align:right">
                        <font class="small">{{ comment.submit_date|date:"P" }} on {{ comment.submit_date|date:"F j, Y" }}
                        {% if perms.comments.change_comment %}| <a href="{% url admin:comments_app_comment_change comment.pk %}">Edit</a>{% endif %}
                        {% if perms.comments.delete_comment %}| <a href="{% url comments-delete comment.pk %}?next={{ object.get_absolute_url }}">Delete</a>{% endif %}</font>
                    </div>
                </div>
                <div class="prepend-top span-15">
                    {% wikify comment.comment %}
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="span-3 last prepend-top">
        {% if comment_list|length > 3 %}
        {% ad user "skyscraper" %}
        {% else %}
        {% ad user "small_box" %}
        {% endif %}
    </div>
    {% endif %}
    {% if user.is_authenticated %}
    {% if object.closed %}
    <h3>This discussion has been closed</h3>
    {% else %}
    {% get_comment_form for object as form %}
    <div id="comment_form" class="span-24 prepend-top">
        <form action="{% comment_form_target %}" method="post">{% csrf_token %}
            <div class="span-10">
                <h2 class="snug">Answer</h2>
                {% for field in form %}
                {% if field.is_hidden %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <p class="hide">{{ form.honeypot }}</p>
                <p>{{ form.comment }}</p>
                <input type="hidden" name="next" value="{{ object.get_absolute_url }}" />
                <input type="submit" name="preview" value="Preview your answer!" />
            </div>
            <div class="span-10 prepend-1 last prepend-top">
                <h3>Discussion options</h3>
                <h4>{% subscription_toggle_link object user request.path %} to this discussion.</h4>
                <h4><a href="/help-desk/#formatting">Formatting tips</a> (Become an expert!)</h4>
                <p>Want to get really daring? Check out <a target="_new" href="http://daringfireball.net/projects/markdown/syntax">markdown syntax</a>.</p>
            </div>
        </form>
    </div>
    {% endif %}
    {% endif %}
</div>

stack/templates/stack/home.html
{% extends "base.html" %}
{% block submast %}
<div class="span-16">
	<h1 class="snug">MTG Q&AMP;A</h1>
	<h2>Think you need a lawyer to understand MTG rules and errata? Think again!</h2>
</div>
<div class="span-8 last">
	{% if user.is_authenticated %}<h1><a href="{% url stack_question_add %}">Ask a question</a></h1>{% endif %}
	<h2><a href="{% url stack_question_list %}">View all questions</a></h2>
</div>
{% endblock %}
{% block body %}
{% if unanswered %}
<h1>Unanswered Q&AMP;A</h1>
{% for question in unanswered %}
{% include "stack/question_snippet.html" %}
{% endfor %}
<hr />
{% endif %}
<h1>Recently Answered</h1>
{% for question in answered|slice:":20" %}
{% include "stack/question_snippet.html" %}
{% endfor %}
{% endblock %}

stack/templates/stack/preview.html
{% extends base_template %}
{% block body %}
<div class="span12">
    {% include "_form_errors.html" %}
    <h1>Question preview</h1>
    <div class="hero-unit">
        {% if question %}
            <h1>{{ question.title }}</h1>
            <h4>Asked by {{ user }} {{ comment_submit_date|timesince }} ago</h4>
            <h3>{{user}}</h3>
        {% endif %}
        {% if comment %}{{ comment }}{% endif %}

    </div>
    <form action="./" method="post">{% csrf_token %}
        {% for field in form %}
            {% if field.is_hidden %}
                {{ field }}
            {% else %}
                {% if field.errors %} {{ field.errors }} {% endif %}
                <p{% if field.errors %} class="error"{% endif %}{% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}>
                    {{ field }}
                </p>
            {% endif %}
        {% endfor %}
        {% if preview_called %}
            <input type="submit" name="submit" class="btn " value=Post" />
        {% endif %}
        <input type="submit" name="preview" class="btn" value="Preview" />
    </form>
</div>
{% endblock %}

stack/templates/stack/question_detail.html
{% extends "base.html" %}
{% load wiki_tags comments_plus_tags stack_tags %}
{% block body %}
<div class="span-22 prepend-1">
	<h2 class="snug">{% wikify instance.title %}{% if perms.stack.change_question %}<sup><a href="{% url admin:stack_question_change instance.pk %}">Edit</a></sup>{% endif %}</h2>
	<h4>Asked by {{ instance.comment.user }}{{ instance.comment.submit_date|timesince }} ago</h4>
	{% wikify instance.comment.comment %}
</div>
{% endblock %}
{% block bottom_stage %}
{% render_answer_stage for instance %}
{% endblock %}

stack/templates/stack/question_list.html
{% extends "base.html" %}
{% block body %}
<h2>MTG Q&AMP;A{% if user.is_authenticated %}&mdash; <a href="{% url stack_question_add %}">Ask a question</a>{% endif %}</h2>
{% for question in object_list %}
{% include "stack/question_snippet.html" %}
{% endfor %}
{% endblock %}

stack/templates/stack/question_snippet.html
{% with question.accepted_answer_id as answered %}
<div class="span-24" style="vertical-align:top">
	<div class="span-2" style="text-align:center;">
		<span style="font-size:25px">{{ question.get_response_count }}</span>
		<br />Responses
	</div>
	<div class="span-2" style="text-align:center;">
		<span style="font-size:25px;">{{ question.views }}</span>
		<br />Views
	</div>
	<div class="span-20 last">
		<h2 class="snug">
			<a style="text-decoration:none;" href="{{ question.get_absolute_url }}">{{ question }}</a>
		</h2>
		<p>
			Asked {{ question.comment.submit_date|timesince }} ago by {{ question.comment.user }}
			{% if answered %}
			<span style="color:green;">
				Answered by {{ question.accepted_answer.user }}
			</span>
			{% endif %}
		</p>
	</div>
</div>
{% endwith %}